borrow and bookcase
awesome-academy/pp1804_lms pull request #17
Opened 2019-03-01 14:00 UTC by doanhvv

2019-03-01 14:00 UTC, doanhvv commented
ready

2019-03-06 11:23 UTC, tranvanmy requested changes
Please check comment

2019-03-06 11:23 UTC, tranvanmy commented on app/Http/Controllers/UserController.php
> +            return redirect()->back()->with('error', 'Rất tiếc, kho đã hết sách, hẹn gặp lại.');
Please use i18n

2019-03-06 11:23 UTC, tranvanmy commented on app/Http/Controllers/UserController.php
> +            return redirect()->route('bookcase')->with('success', 'Bạn đã đăng kí mượn sách thành công, sẽ mất một khoảng thời gian để đơn đăng kí được duyệt.');
Please use i18n

2019-03-06 11:23 UTC, tranvanmy commented on app/Http/Controllers/UserController.php
> +        return redirect()->back()->with('error', 'Ngày mượn sách phải nhỏ hơn hoặc bằng ngày trả sách.');
Please use i18n

2019-03-06 11:23 UTC, tranvanmy commented on app/Http/Controllers/UserController.php
> +}
convention

2019-03-06 11:23 UTC, tranvanmy commented on resources/lang/en/enum.php
> +];
convention

2019-03-06 11:23 UTC, tranvanmy commented on resources/views/frontend/user/bookcase.blade.php
> +                <h1>Tủ sách</h1>
Please use i18n

2019-03-06 11:23 UTC, tranvanmy commented on resources/views/frontend/user/bookcase.blade.php
> +                <p class="text-warning">Vui lòng đọc quy định mượn trả sách của chúng tôi <a href="">tại đây.</a></p>
Please use i18n

2019-03-06 11:23 UTC, tranvanmy commented on resources/views/frontend/user/bookcase.blade.php
> +                                <th>#</th>
Please use i18n

2019-03-06 11:23 UTC, tranvanmy commented on resources/views/frontend/user/bookcase.blade.php
> +                                        @endif
Please use i18n

2019-03-06 11:23 UTC, tranvanmy commented on resources/views/frontend/user/borrow.blade.php
> +                <h1>Mượn sách</h1>
Please use i18n

2019-03-06 11:23 UTC, tranvanmy commented on resources/views/frontend/user/borrow.blade.php
> +                <h3>Tên sách: {{ $book->name }}</h3>
Please use i18n

2019-03-06 11:23 UTC, tranvanmy commented on resources/views/frontend/user/borrow.blade.php
> +                        <input name="endtime" type="date" class="form-control" required>
Please use i18n

2019-03-06 11:23 UTC, tranvanmy commented on routes/web.php
> +    Route::post('user/borrow/{id?}', 'UserController@borrow')->name('borrow');
why use "?"  in route ?????

2019-03-06 11:23 UTC, tranvanmy commented on routes/web.php
> +});
Please remove if not use

2019-03-06 11:29 UTC, tranvanmy commented on app/Http/Controllers/UserController.php
> +            $borrow = Borrow::create([
should use 'firstOrCreate'

2019-03-06 11:29 UTC, tranvanmy commented on app/Http/Controllers/UserController.php
> +            $book->update();
use try { } catch and transaction for function

2019-03-06 11:29 UTC, tranvanmy commented on app/Http/Controllers/UserController.php
> +        return FALSE;
please format this

2019-03-06 11:29 UTC, tranvanmy commented on app/Http/Controllers/UserController.php
> +        if($borrow->user_id == auth()->id()){
convention

2019-03-06 11:29 UTC, tranvanmy commented on resources/views/frontend/book/detail.blade.php
> +                        @else
Please use i18n

2019-03-06 12:11 UTC, tranvanmy commented on routes/web.php
> +    Route::post('user/borrow/{id?}', 'UserController@borrow')->name('borrow');
Why use "?" in route ??

2019-03-06 13:36 UTC, doanhvv commented
ready

2019-03-07 03:07 UTC, tranvanmy approved these changes

2019-03-08 12:24 UTC, tranvanmy commented on app/Http/Controllers/UserController.php
> +
bỏ khoảng trắng đi nhé,

2019-03-08 12:45 UTC, merged